---
title: '[ 적격심사의 전반적인 상황(입찰공고, 입찰 참가자, 실제 낙찰, 부적격 판정, 낙찰하한선 미달) - 추정가격 10억원 미만 ]'
author: "Seo Ji Young"
date: '2022 2 24 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 필요한 세팅
rm(list = ls()); gc(reset = T)
require(readxl); require(dplyr)

```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-01~2021-11-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(26844개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(119개) / 낙찰(100개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(12956개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(12682개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(13888개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(13888개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(13888개) 중 낙찰된 데이터(100개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-11~2021-11-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(4140개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(112개) / 낙찰(100개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(1896개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(1824개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(2243개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(2243개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(2243개) 중 낙찰된 데이터(100개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-21~2021-11-30)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(18125개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(163개) / 낙찰(127개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(6859개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(1824개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(11266개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(11266개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(11266개) 중 낙찰된 데이터(127개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-01~2021-12-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(25180개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(179개) / 낙찰(159개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(9554개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(9322개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(15626개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(15626개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(15626개) 중 낙찰된 데이터(159개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-11~2021-12-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(14252개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(138개) / 낙찰(119개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(5846개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(5516개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(8406개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(8406개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(8406개) 중 낙찰된 데이터(119개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-21~2021-12-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(4739개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(80개) / 낙찰(70개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(1808개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(1768개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(2931개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(2931개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(2931개) 중 낙찰된 데이터(70개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-01~2022-01-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(4093개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(46개) / 낙찰(36개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(1806개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(1758개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(2287개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(2287개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(2287개) 중 낙찰된 데이터(36개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-11~2022-01-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(11918개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(121개) / 낙찰(71개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(4690개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(4308개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(7228개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(7228개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(7228개) 중 낙찰된 데이터(71개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-21~2022-01-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터(11464개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원미만", Excel[, 1]); criteria_2 = grep("10억원 미만", Excel[, 1])
sub_dat = Excel[c(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(99개) / 낙찰(45개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(6186개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(6111개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(5278개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(5278개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(5278개) 중 낙찰된 데이터(45개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```