---
title: '[ 적격심사의 전반적인 상황(입찰공고, 입찰 참가자, 실제 낙찰, 부적격 판정, 낙찰하한선 미달) - 추정가격 10억원 이상 ]'
author: "Seo Ji Young"
date: '2022 2 24 '
output: html_document
---

```{r setup, include=FALSE}
# 필요한 세팅
rm(list = ls()); gc(reset = T)
require(readxl); require(dplyr)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-01~2021-11-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(63개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(4개) / 낙찰(2개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(15개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(13개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(48개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(48개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(48개) 중 낙찰된 데이터(2개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-11~2021-11-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(115개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(16개) / 낙찰(16개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(24개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(10개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(91개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(91개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(91개) 중 낙찰된 데이터(16개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-21~2021-11-30)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(66개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(14개) / 낙찰(12개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(13개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(10개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(53개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(53개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(53개) 중 낙찰된 데이터(12개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-01~2021-12-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(179개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(11개) / 낙찰(9개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(103개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(96개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(76개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(76개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(76개) 중 낙찰된 데이터(9개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-11~2021-12-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(148개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(12개) / 낙찰(10개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(78개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(74개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(70개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(70개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(70개) 중 낙찰된 데이터(10개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-21~2021-12-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(25개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(6개) / 낙찰(5개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(7개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(4개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(18개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(18개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(18개) 중 낙찰된 데이터(5개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-01~2022-01-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(13개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(1개) / 낙찰(1개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(6개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(6개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(7개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(7개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(7개) 중 낙찰된 데이터(1개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-11~2022-01-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(119개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(10개) / 낙찰(6개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(21개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(16개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(98개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(98개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(98개) 중 낙찰된 데이터(6개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-21~2022-01-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 이상인 데이터(84개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("10억원이상", Excel[, 1]); sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(7개) / 낙찰(3개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(13개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(4개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(71개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(71개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 95.5){
    price_score[i, 3] = 40
  }else{
    price_score[i, 3] = 55-2*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(71개) 중 낙찰된 데이터(3개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```