---
title: '[ 가격점수와 낙찰성공률의 관계 - 추정가격 고시금액 미만 ]'
author: "Seo Ji Young"
date: '2022 2 24 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 필요한 세팅
rm(list = ls()); gc(reset = T)
require(readxl); require(dplyr); require(ggplot2)

```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-01~2021-11-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-11~2021-11-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-21~2021-11-30)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-01~2021-12-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-11~2021-12-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-21~2021-12-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot


# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-01~2022-01-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3) + I(가격점수^4), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-11~2022-01-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3) + I(가격점수^4), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-21~2021-01-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 추정가격 10억원 미만인 데이터에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1]); criteria_2 = grep("중기간", Excel[, 1])
sub_dat = Excel[setdiff(criteria, criteria_2), c(1, 3, 5, 6, 7, 8)]

price_dat = sub_dat[, c(3, 4, 6)]
price_dat = price_dat %>% mutate(score = c(1:nrow(price_dat)))
for(i in 1:nrow(price_dat)){
  if(is.na(price_dat[i, 1]) == TRUE){
    price_dat[i, 4] = 0
  }else{
    if(price_dat[i, 1] >= 91.75){
      price_dat[i, 4] = 55
    }else{
      price_dat[i, 4] = 70-4*abs(88-price_dat[i, 1])
    }
  }
}
price_dat

# score_decision : 낙찰된 것 / 안된 것 - 가격점수로 오름차순 정렬
score_decision = price_dat[, c(2, 3, 4)]
score_decision = score_decision %>% arrange(score)
score_decision = score_decision %>% filter(부적격여부 == "N")
score_decision
min(score_decision[, 3]); max(score_decision[, 3])


# my_list : 낙찰된 데이터만 가격점수 구간별로 나눔
score_decision_Yes = score_decision %>% filter(낙찰여부 == "Y")
score_decision_Yes
min(score_decision_Yes[, 3]); max(score_decision_Yes[, 3])

my_list = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision_Yes)){
    if(score_decision_Yes[j, 3] >= i+53 & score_decision_Yes[j, 3] < i+54){
      group[[j]] = score_decision_Yes[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "Y", score = 0)
    }
  }
  group = group %>% do.call(rbind, .)
  my_list[[i]] = group %>% filter(score > 0)
}
my_list

# my_list_2 : 낙찰된 것 / 안된 것 모두 가격점수 구간별로 나눔
my_list_2 = list()
for(i in 1:16){
  group = list()
  for(j in 1:nrow(score_decision)){
    if(score_decision[j, 3] >= i+53 & score_decision[j, 3] < i+54){
      group[[j]] = score_decision[j, ]
    }else{
      group[[j]] = data.frame(부적격여부 = "N", 낙찰여부 = "N", score = 0)
    }
  }
  group = group %>% do.call(rbind,.)
  my_list_2[[i]] = group %>% filter(score > 0)
}

# my_length : 낙찰된 데이터들 중 가격점수 구간에 따른 데이터의 개수를 저장
# my_length_2 : 낙찰된 여부와 관계없이 가격점수 구간에 따른 데이터의 개수를 저장

my_length = c(); my_length_2 = c()
for(i in 1:16){
  my_length[i] = nrow(my_list[[i]])
  my_length_2[i] = nrow(my_list_2[[i]])
}

# final_dat : 가격점수와 낙찰성공률(my_length와 my_length_2 이용)을 저장
final_dat = data.frame(가격점수 = c(54:69), 낙찰성공률 = c(54:69))
for(i in 1:nrow(final_dat)){
  final_dat[i, 2] = my_length[i]/my_length_2[i]
}

final_dat[, 1] = final_dat[, 1] %>% as.numeric()
summary(final_dat[, 2])

# 시각화(산점도 + 회귀분석)
plot = ggplot(data = final_dat) + geom_point(aes(x = 가격점수, y = 낙찰성공률))
plot

res = lm(낙찰성공률~ 가격점수 + I(가격점수^2) + I(가격점수^3) + I(가격점수^4), data = final_dat)
summary(res)
par(mfrow = c(2,2)); plot(res); coef(res)

res_plot = ggplot(final_dat, aes(x = 가격점수, y = 낙찰성공률)) + geom_point() + stat_smooth()
res_plot
```