---
title: '[ 적격심사의 전반적인 상황(입찰공고, 입찰 참가자, 실제 낙찰, 부적격 판정, 낙찰하한선 미달) - 추정가격 고시금액 미만 ]'
author: "Seo Ji Young"
date: '2022 2 24 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 필요한 세팅
rm(list = ls()); gc(reset = T)
require(readxl); require(dplyr)
```

```{r}
# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-01~2021-11-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(60364개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(372개) / 낙찰(328개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(31218개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(30426개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(29146개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(29146개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(29146개) 중 낙찰된 데이터(328개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-11~2021-11-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(52334개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(324개) / 낙찰(290개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(20849개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(20444개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(31485개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(31485개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(31485개) 중 낙찰된 데이터(290개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-11-21~2021-11-30)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(24649개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(447개) / 낙찰(302개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(10844개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(10300개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(13764개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(13764개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(13764개) 중 낙찰된 데이터(302개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-01~2021-12-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(29460개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(499개) / 낙찰(413개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(13584개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(13082개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(15876개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(15876개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(15876개) 중 낙찰된 데이터(413개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-11~2021-12-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(24798개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(317개) / 낙찰(272개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(12840개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(12468개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(11958개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(11958개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(11958개) 중 낙찰된 데이터(272개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2021-12-21~2021-12-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(20673개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(363개) / 낙찰(338개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(10302개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(10002개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(10371개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(10371개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(10371개) 중 낙찰된 데이터(338개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-01~2022-01-10)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(21982개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(122개) / 낙찰(87개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(8210개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(7261개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(13772개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(13772개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(13772개) 중 낙찰된 데이터(87개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-11~2022-01-20)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(43818개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(259개) / 낙찰(214개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(21880개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(20650개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(21937개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(21937개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(21937개) 중 낙찰된 데이터(214개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)

# 엑셀 문서 읽기(낙찰자결정방법, 추정가격, 예정가격, 입찰금액, 입찰률, 부적격여부, 부적격사유, 낙찰여부)
Excel = read_xlsx("./조달청/3-23. 물품 입찰분류별 투찰업체 내역(2022-01-21~2022-01-31)[인덱싱].xlsx") %>% data.frame(stringsAsFactors = F)

# 고시금액 미만인 데이터(22625개)에서 추정가격, 입찰금액 제외한 데이터 인덱싱
criteria = grep("고시금액미만", Excel[, 1])
sub_dat = Excel[criteria, c(1, 3, 5, 6, 7, 8)]

# 낙찰공고(195개) / 낙찰(161개) 각각의 개수 확인
unique_item = unique(sub_dat[, 2]); pick = grep("Y", sub_dat[, 6])
length(unique_item); length(pick)

# 부적격사유 분석(10622개)
fail_item = grep("Y", sub_dat[, 4])
fail_dat = sub_dat[fail_item, c(3, 4, 5)]
nrow(fail_dat)

for(i in 1:nrow(fail_dat)){
  if(is.na(fail_dat[i, 1]) == TRUE){
    fail_dat[i, 1] = 0
  }else{
    fail_dat[i, 1] = fail_dat[i, 1]
  }
}

# 낙찰하한선 미달(10329개)
fail_dat = fail_dat[grep("낙찰", fail_dat[, 3]), c(1, 3)]
nrow(fail_dat); summary(fail_dat[, 1])

# 부적격이 아닌 데이터들(12003개)의 입찰률(입찰가격/예정가격)
good_item = sub_dat[grep("N", sub_dat[, 4]), 3]
length(good_item); summary(good_item)

# 부적격이 아닌 데이터들(12003개)의 가격점수 구하기
price_score = sub_dat[grep("N", sub_dat[, 4]), c(3, 6)] %>% data.frame(stringsAsFactors = F)
price_score = price_score %>% mutate(score = c(1:nrow(price_score)))

for(i in 1:nrow(price_score)){
  if(price_score[i, 1] >= 91.75){
    price_score[i, 3] = 55
  }else{
    price_score[i, 3] = 70-4*abs(88-price_score[i, 1])
  }
}
price_score
summary(price_score[, 3])

# 부적격이 아닌 데이터들(12003개) 중 낙찰된 데이터(161개)들의 가격점수 구하기
sub_price_score = price_score[grep("Y", price_score[, 2]), c(1, 3)]
summary(sub_price_score)
```